[package]
name = "barista"
description = "A launcher for Rhythm Heaven Megamix mods"
version = "0.1.0"
edition = "2018"

[dependencies]
ctru-rs = { path = "../3ds-rust-env/ctru-rs/ctru-rs" }
ctru-sys = { path = "../3ds-rust-env/ctru-rs/ctru-sys" }
citro2d = {path = "citro2d"}
ui = {path = "ui"}

[profile.dev]
lto = true

[profile.release]
lto = true
