[package]
name = "barista"
description = "A launcher for Rhythm Heaven Megamix mods"
authors = ["patataofcourse"]
version = "0.1.0"
edition = "2021"

[dependencies]
ctru-rs = { git = "https://github.com/rust3ds/ctru-rs.git" }
ctru-sys = { git = "https://github.com/rust3ds/ctru-rs.git" }
barista-ui = { path = "library/ui" }
libc = "0.2"
bytestream = "0.4"

[build_dependencies]
cc = "1.0"

[features]
default = []
jp = []
audio = []