[package]
name = "barista"
description = "A launcher for Rhythm Heaven Megamix mods"
version = "0.1.0"
edition = "2018"

[dependencies]
ctru-rs = { git = "https://github.com/rust3ds/ctru-rs.git" }
ctru-sys = { git = "https://github.com/rust3ds/ctru-rs.git" }
barista-ui = { path = "library/ui" }
libc = "0.2"
bytestream = "0.4"

[profile.dev]
lto = true

[profile.release]
lto = true

[features]
default = []
jp = []
audio = []