// Megamix mode
pub const SLOT_NAMES_DEFAULT: [&str; 0x68] = [
    "Clappy Trio",
    "Sneaky Spirits",
    "Rhythm Tweezers",
    "Glee Club",
    "Rhythm Rally",
    "Fillbots",
    "Shoot-'em-up",
    "Air Rally",
    "Micro-Row",
    "Flipper Flop",
    "Figure Fighter",
    "Fruit Basket",
    "First Contact",
    "Catchy Tune",
    "Lum-BEAR-jack",
    "Spaceball",
    "Clappy Trio 2",
    "Sneaky Spirits 2",
    "Rhythm Tweezers 2",
    "Bouncy Road",
    "Marching Orders",
    "Night Walk",
    "Quiz Show",
    "Bunny Hop",
    "Rat Race",
    "Power Calligraphy",
    "Space Dance",
    "Tap Trial",
    "Ninja Bodyguard",
    "Airboarder",
    "Lockstep",
    "Blue Birds",
    "Dazzles",
    "Freeze Frame",
    "Glee Club 2",
    "Frog Hop",
    "Fan Club",
    "Dog Ninja",
    "Rhythm Rally 2",
    "Fillbots 2",
    "Shoot-'em-up 2",
    "Big Rock Finish",
    "Munchy Monk",
    "Built to Scale",
    "Air Rally 2",
    "Exhibition Match",
    "Flock Step",
    "Cheer Readers",
    "Double Date",
    "Catch of the Day",
    "Micro-Row 2",
    "Fork Lifter",
    "Hole in One",
    "Flipper Flop 2",
    "Ringside",
    "Working Dough",
    "Figure Fighter 2",
    "Love Rap",
    "Bossa Nova",
    "Screwbot Factory",
    "Launch Party",
    "Board Meeting",
    "Samurai Slice",
    "See-Saw",
    "Packing Pests",
    "Monkey Watch",
    "Blue Bear",
    "Animal Acrobat",
    "Tongue Lashing",
    "Super Samurai Slice",
    "Fruit Basket 2",
    "Second Contact",
    "Pajama Party",
    "Catchy Tune 2",
    "Sumo Brothers",
    "Tangotronic 3000",
    "Kitties!",
    "Lum-BEAR-jack 2",
    "Snappy Trio",
    "Cosmic Dance",
    "Tap Trial 2",
    "Jumpin' Jazz",
    "Fan Club 2",
    "Cosmic Rhythm Rally",
    "Hole in One 2",
    "Working Dough 2",
    "Figure Fighter 3",
    "Jungle Gymnast",
    "Super Samurai Slice 2",
    "Karate Man",
    "Karate Man Returns",
    "Karate Man Kicks",
    "Karate Man Combos",
    "Karate Man Senior",
    "Lush Remix",
    "Final Remix",
    "Honeybee Remix",
    "Machine Remix",
    "Citrus Remix",
    "Donut Remix",
    "Barbershop Remix",
    "Songbird Remix",
    "Left-Hand Remix",
    "Right-Hand Remix",
];

// Original mode
pub const SLOT_NAMES_NORETCON: &[&str] = &["Clappy Trio 0", "Sneaky Spirits 0"];

// For both Megamix and original mode
pub const SLOT_NAMES_GATE: [&str; 0x14] = [
    "Sick Beats (easy)",
    "Sick Beats (medium)",
    "Sick Beats (hard)",
    "Sick Beats (endless)",
    "Coin Toss (easy)",
    "Coin Toss (medium)",
    "Coin Toss (hard)",
    "Coin Toss (endless)",
    "Clap Trap (easy)",
    "Clap Trap (medium)",
    "Clap Trap (hard)",
    "Clap Trap (endless)",
    "Charging Chicken (easy)",
    "Charging Chicken (medium)",
    "Charging Chicken (hard)",
    "Charging Chicken (endless)",
    "Sick Beats (practice)",
    "Coin Toss (practice)",
    "Clap Trap (practice)",
    "Charging Chicken (practice)",
];

// Internal mode
pub const SLOT_NAMES_INTERNAL_SIMPLE: &[&str] = &["Clappy Trio (S)", "Sneaky Spirits (S)"];

// Debug mode internal names
pub const SLOT_NAMES_INTERNAL: [&str; 0x68] = [
    "agbClapS",
    "agbGhostS",
    "agbHairS",
    "ntrChorusS",
    "ntrPingpongS",
    "ntrRobotS",
    "ntrShootingS",
    "rvlBadmintonS",
    "rvlFleaS",
    "rvlGomaS",
    "rvlMuscleS",
    "ctrFruitbasketS",
    "ctrInterpreterS",
    "ctrStepS",
    "ctrWoodCatS",
    "agbBatterL",
    "agbClapL",
    "agbGhostL",
    "agbHairL",
    "agbHoppingL",
    "agbMarcherL",
    "agbNightWalkL",
    "agbQuizL",
    "agbRabbitL",
    "agbRatL",
    "agbShujiL",
    "agbSpaceDanceL",
    "agbTapL",
    "agbTonoL",
    "ntrAirboardL",
    "ntrBackbeatL",
    "ntrBlueBirdsL",
    "ntrBoxShowL",
    "ntrCameraManL",
    "ntrChorusL",
    "ntrFrogL",
    "ntrIdolL",
    "ntrNinjaL",
    "ntrPingpongL",
    "ntrRobotL",
    "ntrShootingL",
    "ntrShortLiveL",
    "ntrShugyoL",
    "rvlAssembleL",
    "rvlBadmintonL",
    "rvlBattingL",
    "rvlBirdL",
    "rvlBookL",
    "rvlDateL",
    "rvlFishingL",
    "rvlFleaL",
    "rvlFork",
    "rvlGolfL",
    "rvlGomaL",
    "rvlInterviewL",
    "rvlManjuL",
    "rvlMuscleL",
    "rvlRapL",
    "rvlRecieveL",
    "rvlRobotL",
    "rvlRocketL",
    "rvlRotationL",
    "rvlSamuraiL",
    "rvlSeesawL",
    "rvlSortL",
    "rvlWatchL",
    "ctrBearL",
    "ctrBlancoL",
    "ctrChameleonL",
    "ctrDotSamuraiL",
    "ctrFruitBasketL",
    "ctrInterpreterL",
    "ctrPillowL",
    "ctrStepL",
    "ctrSumouL",
    "ctrTangoL",
    "ctrTeppanL",
    "ctrWoodCatL",
    "agbClapA",
    "agbSpaceDanceA",
    "agbTapA",
    "ntrFrogA",
    "ntrIdolA",
    "ntrPingpongA",
    "rvlGolfA",
    "rvlManjuA",
    "rvlMuscleA",
    "ctrBlancoA",
    "ctrDotSamuraiA",
    "rvlKarate0",
    "rvlKarate1",
    "rvlKarate2",
    "rvlKarate3",
    "rvlKarate4",
    "remixLED",
    "remixTED",
    "remix00",
    "remix01",
    "remix02",
    "remix03",
    "remix04",
    "remix05",
    "remix06",
    "remix07",
];

pub const SLOT_NAMES_INTERNAL_GATE: [&str; 0x14] = [
    "agbVirus00",
    "agbVirus01",
    "agbVirus02",
    "agbVirusEndless",
    "ntrCoinToss00",
    "ntrCoinToss01",
    "ntrCoinToss02",
    "ntrCoinTossEndless",
    "rvlSword00",
    "rvlSword01",
    "rvlSword02",
    "rvlSwordEndless",
    "ctrChicken00",
    "ctrChicken01",
    "ctrChicken02",
    "ctrChickenEndless",
    "agbVirusPractice",
    "ntrCoinTossPractice",
    "rvlSwordPractice",
    "ctrChickenPractice",
];

// Infernal mode
// In case we ever go back to that, here's a nano-style line cutoff: "\x1b[30;47m>\x1b[37;40m"
pub const SLOT_NAMES_INFERNAL: &[&str] = &[

];

pub const SLOT_NAMES_INFERNAL_GATE: [&str; 0x14] = [
    "agbHitmegeton (expensive)",
    "agbHitmegeton (pepper)",
    "agbHitmegeton (true)",
    "agbHitmegeton (the end is n",
    "Drum Lessons (expensive)",
    "Drum Lessons (pepper)",
    "Drum Lessons (true)",
    "Drum Lessons (the end is ne",
    "Pretentious nonsense (expen",
    "Pretentious nonsense (peppe",
    "Pretentious nonsense (true)",
    "Pretentious nonsense (the e",
    "chiken (expensive)",
    "chiken (pepper)",
    "chiken (true)",
    "chiken (the end is never th",
    "agbHitmegeton (assets)",
    "Drum Lessons (assets)",
    "Pretentious nonsense (asset",
    "chiken (assets)",
];
