// Megamix mode
pub const SLOT_NAMES_DEFAULT: &[&str] = &[
    "Clappy Trio",
    "Sneaky Spirits",
    "Rhythm Tweezers",
    "Glee Club",
    "Rhythm Rally",
    "Fillbots",
    "Shoot-'em-up",
    "Air Rally",
    "Micro-Row",
    "Flipper Flop",
    "Figure Fighter",
    "Fruit Basket",
    "First Contact",
    "Catchy Tune",
    "Lum-BEAR-jack",
    "Spaceball",
    "Clappy Trio 2",
];

// Original mode
pub const SLOT_NAMES_NORETCON: &[&str] = &["Clappy Trio 0", "Sneaky Spirits 0"];

// For both Megamix and original mode
pub const SLOT_NAMES_GATE: [&str; 0x14] = [
    "Sick Beats (easy)",
    "Sick Beats (medium)",
    "Sick Beats (hard)",
    "Sick Beats (endless)",
    "Coin Toss (easy)",
    "Coin Toss (medium)",
    "Coin Toss (hard)",
    "Coin Toss (endless)",
    "Clap Trap (easy)",
    "Clap Trap (medium)",
    "Clap Trap (hard)",
    "Clap Trap (endless)",
    "Charging Chicken (easy)",
    "Charging Chicken (medium)",
    "Charging Chicken (hard)",
    "Charging Chicken (endless)",
    "Sick Beats (practice)",
    "Coin Toss (practice)",
    "Clap Trap (practice)",
    "Charging Chicken (practice)",
];

// Internal mode
pub const SLOT_NAMES_INTERNAL_SIMPLE: &[&str] = &["Clappy Trio (S)", "Sneaky Spirits (S)"];

// Debug mode internal names
pub const SLOT_NAMES_INTERNAL: [&str; 0x68] = [
    "agbClapS",
    "agbGhostS",
    "agbHairS",
    "ntrChorusS",
    "ntrPingpongS",
    "ntrRobotS",
    "ntrShootingS",
    "rvlBadmintonS",
    "rvlFleaS",
    "rvlGomaS",
    "rvlMuscleS",
    "ctrFruitbasketS",
    "ctrInterpreterS",
    "ctrStepS",
    "ctrWoodCatS",
    "agbBatterL",
    "agbClapL",
    "agbGhostL",
    "agbHairL",
    "agbHoppingL",
    "agbMarcherL",
    "agbNightWalkL",
    "agbQuizL",
    "agbRabbitL",
    "agbRatL",
    "agbShujiL",
    "agbSpaceDanceL",
    "agbTapL",
    "agbTonoL",
    "ntrAirboardL",
    "ntrBackbeatL",
    "ntrBlueBirdsL",
    "ntrBoxShowL",
    "ntrCameraManL",
    "ntrChorusL",
    "ntrFrogL",
    "ntrIdolL",
    "ntrNinjaL",
    "ntrPingpongL",
    "ntrRobotL",
    "ntrShootingL",
    "ntrShortLiveL",
    "ntrShugyoL",
    "rvlAssembleL",
    "rvlBadmintonL",
    "rvlBattingL",
    "rvlBirdL",
    "rvlBookL",
    "rvlDateL",
    "rvlFishingL",
    "rvlFleaL",
    "rvlFork",
    "rvlGolfL",
    "rvlGomaL",
    "rvlInterviewL",
    "rvlManjuL",
    "rvlMuscleL",
    "rvlRapL",
    "rvlRecieveL",
    "rvlRobotL",
    "rvlRocketL",
    "rvlRotationL",
    "rvlSamuraiL",
    "rvlSeesawL",
    "rvlSortL",
    "rvlWatchL",
    "ctrBearL",
    "ctrBlancoL",
    "ctrChameleonL",
    "ctrDotSamuraiL",
    "ctrFruitBasketL",
    "ctrInterpreterL",
    "ctrPillowL",
    "ctrStepL",
    "ctrSumouL",
    "ctrTangoL",
    "ctrTeppanL",
    "ctrWoodCatL",
    "agbClapA",
    "agbSpaceDanceA",
    "agbTapA",
    "ntrFrogA",
    "ntrIdolA",
    "ntrPingpongA",
    "rvlGolfA",
    "rvlManjuA",
    "rvlMuscleA",
    "ctrBlancoA",
    "ctrDotSamuraiA",
    "rvlKarate0",
    "rvlKarate1",
    "rvlKarate2",
    "rvlKarate3",
    "rvlKarate4",
    "remixLED",
    "remixTED",
    "remix00",
    "remix01",
    "remix02",
    "remix03",
    "remix04",
    "remix05",
    "remix06",
    "remix07",
];

pub const SLOT_NAMES_INTERNAL_GATE: [&str; 0x14] = [
    "agbVirus00",
    "agbVirus01",
    "agbVirus02",
    "agbVirusEndless",
    "ntrCoinToss00",
    "ntrCoinToss01",
    "ntrCoinToss02",
    "ntrCoinTossEndless",
    "rvlSword00",
    "rvlSword01",
    "rvlSword02",
    "rvlSwordEndless",
    "ctrChicken00",
    "ctrChicken01",
    "ctrChicken02",
    "ctrChickenEndless",
    "agbVirusPractice",
    "ntrCoinTossPractice",
    "rvlSwordPractice",
    "ctrChickenPractice",
];
