// Megamix mode
pub const SLOT_NAMES_DEFAULT: [&str; 0x68] = [
    "Clappy Trio",
    "Sneaky Spirits",
    "Rhythm Tweezers",
    "Glee Club",
    "Rhythm Rally",
    "Fillbots",
    "Shoot-'em-up",
    "Air Rally",
    "Micro-Row",
    "Flipper Flop",
    "Figure Fighter",
    "Fruit Basket",
    "First Contact",
    "Catchy Tune",
    "Lum-BEAR-jack",
    "Spaceball",
    "Clappy Trio 2",
    "Sneaky Spirits 2",
    "Rhythm Tweezers 2",
    "Bouncy Road",
    "Marching Orders",
    "Night Walk",
    "Quiz Show",
    "Bunny Hop",
    "Rat Race",
    "Power Calligraphy",
    "Space Dance",
    "Tap Trial",
    "Ninja Bodyguard",
    "Airboarder",
    "Lockstep",
    "Blue Birds",
    "Dazzles",
    "Freeze Frame",
    "Glee Club 2",
    "Frog Hop",
    "Fan Club",
    "Dog Ninja",
    "Rhythm Rally 2",
    "Fillbots 2",
    "Shoot-'em-up 2",
    "Big Rock Finish",
    "Munchy Monk",
    "Built to Scale",
    "Air Rally 2",
    "Exhibition Match",
    "Flock Step",
    "Cheer Readers",
    "Double Date",
    "Catch of the Day",
    "Micro-Row 2",
    "Fork Lifter",
    "Hole in One",
    "Flipper Flop 2",
    "Ringside",
    "Working Dough",
    "Figure Fighter 2",
    "Love Rap",
    "Bossa Nova",
    "Screwbot Factory",
    "Launch Party",
    "Board Meeting",
    "Samurai Slice",
    "See-Saw",
    "Packing Pests",
    "Monkey Watch",
    "Blue Bear",
    "Animal Acrobat",
    "Tongue Lashing",
    "Super Samurai Slice",
    "Fruit Basket 2",
    "Second Contact",
    "Pajama Party",
    "Catchy Tune 2",
    "Sumo Brothers",
    "Tangotronic 3000",
    "Kitties!",
    "Lum-BEAR-jack 2",
    "Snappy Trio",
    "Cosmic Dance",
    "Tap Trial 2",
    "Jumpin' Jazz",
    "Fan Club 2",
    "Cosmic Rhythm Rally",
    "Hole in One 2",
    "Working Dough 2",
    "Figure Fighter 3",
    "Jungle Gymnast",
    "Super Samurai Slice 2",
    "Karate Man",
    "Karate Man Returns",
    "Karate Man Kicks",
    "Karate Man Combos",
    "Karate Man Senior",
    "Lush Remix",
    "Final Remix",
    "Honeybee Remix",
    "Machine Remix",
    "Citrus Remix",
    "Donut Remix",
    "Barbershop Remix",
    "Songbird Remix",
    "Left-Hand Remix",
    "Right-Hand Remix",
];

// Original mode
pub const SLOT_NAMES_NORETCON: [&str; 0x68] = [
    "Clappy Trio (Prequel)",
    "Sneaky Spirits (Prequel)",
    "Rhythm Tweezers (Prequel)",
    "Glee Club (Prequel)",
    "Rhythm Rally (Prequel)",
    "Fillbots (Prequel)",
    "Shoot-'em-up (Prequel)",
    "Air Rally (Prequel)",
    "Micro-Row (Prequel)",
    "Flipper Flop (Prequel)",
    "Figure Fighter (Prequel)",
    "Fruit Basket (Prequel)",
    "First Contact (Prequel)",
    "Catchy Tune (Prequel)",
    "Lum-BEAR-jack (Prequel)",
    "Spaceball",
    "Clappy Trio",
    "Sneaky Spirits",
    "Rhythm Tweezers",
    "Bouncy Road",
    "Marching Orders",
    "Night Walk",
    "Quiz Show",
    "Bunny Hop",
    "Rat Race",
    "Power Calligraphy",
    "Space Dance",
    "Tap Trial",
    "Ninja Bodyguard",
    "Airboarder",
    "Lockstep",
    "Blue Birds",
    "Dazzles",
    "Freeze Frame",
    "Glee Club",
    "Frog Hop",
    "Fan Club",
    "Dog Ninja",
    "Rhythm Rally",
    "Fillbots",
    "Shoot-'em-up",
    "Big Rock Finish",
    "Munchy Monk",
    "Built to Scale",
    "Air Rally",
    "Exhibition Match",
    "Flock Step",
    "Cheer Readers",
    "Double Date",
    "Catch of the Day",
    "Micro-Row",
    "Fork Lifter",
    "Hole in One",
    "Flipper Flop",
    "Ringside",
    "Working Dough",
    "Figure Fighter",
    "Love Rap",
    "Bossa Nova",
    "Screwbot Factory",
    "Launch Party",
    "Board Meeting",
    "Samurai Slice",
    "See-Saw",
    "Packing Pests",
    "Monkey Watch",
    "Blue Bear",
    "Animal Acrobat",
    "Tongue Lashing",
    "Super Samurai Slice",
    "Fruit Basket",
    "Second Contact",
    "Pajama Party",
    "Catchy Tune",
    "Sumo Brothers",
    "Tangotronic 3000",
    "Kitties!",
    "Lum-BEAR-jack",
    "Snappy Trio",
    "Cosmic Dance",
    "Tap Trial 2",
    "Jumpin' Jazz",
    "Fan Club 2",
    "Cosmic Rhythm Rally",
    "Hole in One 2",
    "Working Dough 2",
    "Figure Fighter 2",
    "Jungle Gymnast",
    "Super Samurai Slice 2",
    "Karate Man (Prequel)",
    "Karate Man Returns",
    "Karate Man Kicks",
    "Karate Man Combos",
    "Karate Man Senior",
    "Lush Remix",
    "Final Remix",
    "Honeybee Remix",
    "Machine Remix",
    "Citrus Remix",
    "Donut Remix",
    "Barbershop Remix",
    "Songbird Remix",
    "Left-Hand Remix",
    "Right-Hand Remix",
];

// For both Megamix and original mode
pub const SLOT_NAMES_GATE: [&str; 0x14] = [
    "Sick Beats (easy)",
    "Sick Beats (medium)",
    "Sick Beats (hard)",
    "Sick Beats (endless)",
    "Coin Toss (easy)",
    "Coin Toss (medium)",
    "Coin Toss (hard)",
    "Coin Toss (endless)",
    "Clap Trap (easy)",
    "Clap Trap (medium)",
    "Clap Trap (hard)",
    "Clap Trap (endless)",
    "Charging Chicken (easy)",
    "Charging Chicken (medium)",
    "Charging Chicken (hard)",
    "Charging Chicken (endless)",
    "Sick Beats (practice)",
    "Coin Toss (practice)",
    "Clap Trap (practice)",
    "Charging Chicken (practice)",
];

// Debug mode internal names
pub const SLOT_NAMES_INTERNAL: [&str; 0x68] = [
    "agbClapS",
    "agbGhostS",
    "agbHairS",
    "ntrChorusS",
    "ntrPingpongS",
    "ntrRobotS",
    "ntrShootingS",
    "rvlBadmintonS",
    "rvlFleaS",
    "rvlGomaS",
    "rvlMuscleS",
    "ctrFruitbasketS",
    "ctrInterpreterS",
    "ctrStepS",
    "ctrWoodCatS",
    "agbBatterL",
    "agbClapL",
    "agbGhostL",
    "agbHairL",
    "agbHoppingL",
    "agbMarcherL",
    "agbNightWalkL",
    "agbQuizL",
    "agbRabbitL",
    "agbRatL",
    "agbShujiL",
    "agbSpaceDanceL",
    "agbTapL",
    "agbTonoL",
    "ntrAirboardL",
    "ntrBackbeatL",
    "ntrBlueBirdsL",
    "ntrBoxShowL",
    "ntrCameraManL",
    "ntrChorusL",
    "ntrFrogL",
    "ntrIdolL",
    "ntrNinjaL",
    "ntrPingpongL",
    "ntrRobotL",
    "ntrShootingL",
    "ntrShortLiveL",
    "ntrShugyoL",
    "rvlAssembleL",
    "rvlBadmintonL",
    "rvlBattingL",
    "rvlBirdL",
    "rvlBookL",
    "rvlDateL",
    "rvlFishingL",
    "rvlFleaL",
    "rvlFork",
    "rvlGolfL",
    "rvlGomaL",
    "rvlInterviewL",
    "rvlManjuL",
    "rvlMuscleL",
    "rvlRapL",
    "rvlRecieveL",
    "rvlRobotL",
    "rvlRocketL",
    "rvlRotationL",
    "rvlSamuraiL",
    "rvlSeesawL",
    "rvlSortL",
    "rvlWatchL",
    "ctrBearL",
    "ctrBlancoL",
    "ctrChameleonL",
    "ctrDotSamuraiL",
    "ctrFruitBasketL",
    "ctrInterpreterL",
    "ctrPillowL",
    "ctrStepL",
    "ctrSumouL",
    "ctrTangoL",
    "ctrTeppanL",
    "ctrWoodCatL",
    "agbClapA",
    "agbSpaceDanceA",
    "agbTapA",
    "ntrFrogA",
    "ntrIdolA",
    "ntrPingpongA",
    "rvlGolfA",
    "rvlManjuA",
    "rvlMuscleA",
    "ctrBlancoA",
    "ctrDotSamuraiA",
    "rvlKarate0",
    "rvlKarate1",
    "rvlKarate2",
    "rvlKarate3",
    "rvlKarate4",
    "remixLED",
    "remixTED",
    "remix00",
    "remix01",
    "remix02",
    "remix03",
    "remix04",
    "remix05",
    "remix06",
    "remix07",
];

pub const SLOT_NAMES_INTERNAL_GATE: [&str; 0x14] = [
    "agbVirus00",
    "agbVirus01",
    "agbVirus02",
    "agbVirusEndless",
    "ntrCoinToss00",
    "ntrCoinToss01",
    "ntrCoinToss02",
    "ntrCoinTossEndless",
    "rvlSword00",
    "rvlSword01",
    "rvlSword02",
    "rvlSwordEndless",
    "ctrChicken00",
    "ctrChicken01",
    "ctrChicken02",
    "ctrChickenEndless",
    "agbVirusPractice",
    "ntrCoinTossPractice",
    "rvlSwordPractice",
    "ctrChickenPractice",
];

// Infernal mode
// In case we ever go back to that, here's a nano-style line cutoff: "\x1b[30;47m>\x1b[37;40m"
pub const SLOT_NAMES_INFERNAL: [&str; 0x68] = [
    "burn it (fire emoji)",
    "agbAimu",
    "THE MEMES",
    "unimplemented uwu", //TODO: Glee Club 0
    "Ping-pong Any%",
    "unimplemented uwu", //TODO: Fillbots 0
    "ntrAnime",
    "unimplemented uwu", //TODO: Air Rally 0
    "unimplemented uwu", //TODO: Micro-Row 0
    "unimplemented uwu", //TODO: Flipper Flop 0
    "Fartless Figure",
    "unimplemented uwu", //TODO: Fruit Basket 0
    "unimplemented uwu", //TODO: First Contact
    "BDGBbEb",
    "the gay one :)",
    "agbShibafu",
    "rvlTebyoushi",
    "rvlWhiteGuys",
    "| | | |||| | |",
    "Not Bunny Hop",
    "agbHandCrap",
    "agb4BeatKeep",
    "rvlGomaA",
    "Actual Bunny Hop",  //TODO: Bunny Hop
    "unimplemented uwu", //TODO: Rat Race
    "rvlShuji",
    "agbTRex",
    "rvlTap (no not that one)",
    "salsa walsa :3",
    "unimplemented uwu", //TODO: Airboarder (ntrFushigijan?)
    "Lockstep",
    "World War I",
    "part of ntrAdultMan",
    "Flipper Snapper",
    "ntrMoody",
    "unimplemented uwu", //TODO: Frog Hop
    "unimplemented uwu", //TODO: Fan Club
    "unimplemented uwu", //TODO: Dog Ninja
    "ntrRemix8",
    "unimplemented uwu", //TODO: Return of Fillbots
    "Karate Man Kicks! 2",
    "ntrBathRoman",
    "ntrFlea",
    "Polyrhythm Wii",
    "unimplemented uwu", //TODO: Return of Air Rally
    "unimplemented uwu", //TODO: Exhibition Match
    "Flockstep",
    "OOOO",
    "A W for you",
    "Women want me",
    "rvlShugyo",
    "Fork to eat",
    "rvlBaseball",
    "unimplemented uwu", //TODO: Return of Flipper Flop
    "THE MEMES 2",
    "OSHA nightmare",
    "Figure Farter",
    "for sure",
    "rvlSex",
    "(lenny face)",
    "unimplemented uwu", //TODO: Launch Party
    "rvlRotationS",
    "Samurai Slice",     //TODO: boring
    "unimplemented uwu", //TODO: See-Saw
    "remix10-v2-final.png",
    "Clockstep",
    "If I were green I would die",
    "unimplemented uwu", //TODO: Animal Acrobat
    "ctrTutorial",
    "Samurai SIice",     //TODO: ok i get the joke now but still kinda boring
    "unimplemented uwu", //TODO: Return of Fruit Basket
    "unimplemented uwu", //TODO: Second Contact
    "Love Lab",
    "Luigi's Mansion (2001)",
    "ctrBread",
    "ctrSocial",
    "^OwO^",
    "theyre even gayer now :3",
    "agbTebyoushiDexy",
    "better space dance",
    "AAAAA YES YES YES YES YES Y",
    "unimplemented uwu", //TODO: Jumpin' Jazz
    "unimplemented uwu", //TODO: Fan Club 2
    "Wrist exterminator",
    "omg she transitioned good f-",
    "           .",
    "Figure Ex-Farter",
    "unimplemented uwu", //TODO: Jungle Gymnast
    "<garbled text goes here>",
    "the bad one",
    "the good one",
    "another one",
    "the last one",
    "the kaizo one",
    "A light-emitting diode is a-",
    "ur mom",
    "trans rights!",
    "at least no shitty trumpets",
    "1st Remix 1",
    "oh yeah that one",
    "Taylor Swift - Red (2012)",
    "Endful Remix",
    "remix 10",
    "remix 10 (again)",
];

pub const SLOT_NAMES_INFERNAL_GATE: [&str; 0x14] = [
    "agbHitmegeton (expensive)",
    "agbHitmegeton (pepper)",
    "agbHitmegeton (true)",
    "agbHitmegeton (the end is n",
    "Drum Lessons (expensive)",
    "Drum Lessons (pepper)",
    "Drum Lessons (true)",
    "Drum Lessons (the end is ne",
    "Pretentious nonsense (expen",
    "Pretentious nonsense (peppe",
    "Pretentious nonsense (true)",
    "Pretentious nonsense (the e",
    "chiken (expensive)",
    "chiken (pepper)",
    "chiken (true)",
    "chiken (the end is never th",
    "agbHitmegeton (assets)",
    "Drum Lessons (assets)",
    "Pretentious nonsense (asset",
    "chiken (assets)",
];
